### ISSUE TITLE
Break in character encoding

### ISSUE THREAD

**Issue by chrisbrasington** [chrisbrasington/tunefind-playlist-generator#1]
In windows at least...

https://www.tunefind.com/api/v1/show/supernatural/season-1/5253
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    get_show('supernatural')
  File "main.py", line 45, in get_show
    print song['name'], '-', song['artist']['name'], '(', song['confidence'], ')'
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u201c' in position 24: character maps to <undefined>

**Comment by chrisbrasington** [comment]
Only affects printing to console. Resolved.
